### ISSUE TITLE
웹사이트에 필요한 기능

### ISSUE THREAD

**Issue by seungwonpark** [gshslatexintro/gshslatexintro.github.io#1]
우선 이 웹사이트에 추가적으로 필요한 기능들을 모아 봅시다. 대부분의 경우 GitHub Page Generator에서 html밖에 지원하지 않아서 구현하지 못한 기능들입니다. 곧 @CSNE 의 라즈베리파이 서버를 이용해 사이트를 옮기고 php 로 짤 계획입니다.
- repository의 용량 자동 업데이트
- 문서의 목록 자동 업데이트

**Comment by CSNE** [comment]
일단 PHP + Python으로 .zip 파일 용량 갱신은 구현
해 둔 상태입니다. 자동 갱신이 안 되는 버그가 있긴 하지만...

**Comment by seungwonpark** [comment]
아예 이 repository 의 `php-site` branch 도 1시간 주기로 Pull 하는 건 어떨까요

여기에서 index.php 를 고쳤을 때 매번 pull 하기는 귀찮으니까...

**Comment by seungwonpark** [comment]
이전에 해당 기능을 구현하셨다고 했는데

웹사이트 코드가 자동갱신되지 않는 것 같습니다.

아래와 같이 두 개의 Update index.php 커밋을 했는데 웹사이트에 수정사항이 반영되지 않는군요.

1b9d8f4e1471bcf8ccf81b8271a6ff907dcb89a5

5c789ab73d56c7aee55d7c25fb2e29f1b3c1a671

**Comment by seungwonpark** [comment]
구현해주셨군요.

**Comment by seungwonpark** [comment]
웹사이트 소스 업데이트가 안돼요 ㅠㅠ

1시간 주기로 정각에 pull 하게 해주신다고 했었는데...

**Comment by seungwonpark** [comment]
Everything works well. Merge conflict has been resolved around yesterday 15:40. 👍
