### ISSUE TITLE
파일들을 남겨놓아야 하나요?

### ISSUE THREAD

**Issue by Namnamseo** [gshslatexintro/gshslatexintro.github.io#3]
지금 이 리포지터리의 존재 목적은 github.io 도메인의 페이지를 유지하고, 요청이 들어오면 latex.gs.hs.kr로 보내주는 것입니다. 때문에 index.php 이외의 파일들은 필요하지 않습니다.
혼동을 피하기 위해서 리포지터리에 남아있는 다른 파일들을 지우는 것이 좋지 않나 생각합니다.

규범집에서는 이 리포지터리에 대해 다음과 같이 말하고 있습니다.

> 2016년 9월 10일 이후로 모두 latex.gs.hs.kr으로 리다이렉트를 걸고, 수정을 금지하는 것을 원칙으로 한다.

어떤가요?

**Comment by Namnamseo** [comment]
`master` 브랜치와 `php_site` 브랜치가 있는데, `php_site` 브랜치를 없애고 `master` 브랜치의 `index.html`을 제외한 파일들을 제거하는 게 적절할 것 같습니다.

**Comment by seungwonpark** [comment]
네. 저 정도만 남겨두어도 현 도메인으로의 리다이렉션에는 문제가 없을 것으로 보입니다. index.html 만 남겨주세요.

**Comment by seungwonpark** [comment]
@Kim-kyeongtae `php_site` 브랜치의 파일들을 전부 삭제하는 것 뿐만 아니라, 브랜치 자체를 삭제해 주시기 바랍니다.

**Comment by seungwonpark** [comment]
@Kim-kyeongtae  또한, index.html을 없애고 index.php를 만들어 놓으셨던데, github.io 도메인은 php를 지원하지 않으므로 index.html로 바꾸어야 할 것 같습니다.

추가적으로 설명을 드리자면, master 브랜치는 github.io 도메인에 해당되고, php_site 브랜치는 32기 양찬솔 학생의 라즈베리파이 서버 및 도메인에 해당되는 것이었습니다. 후자는 php를 지원했으나 전자는 그렇지 않습니다.

**Comment by Namnamseo** [comment]
`php_site` 브랜치를 제거하고, master 브랜치에 `index.html` 파일을 배치하였습니다.
GitHub Pages 빌드 성공 후 접속, 그리고 리다이렉트 되는 것까지 확인했습니다.
이슈 닫아도 될 것 같습니다.
